version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -r devrequirements.txt
      - run: pylint snow***REMOVED***.main
